# Generated by Django 4.1 on 2022-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('specifications', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
