# Generated by Django 4.1 on 2022-12-02 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
