# Generated by Django 4.1 on 2022-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_asset_date_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('specifications', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_entered', models.DateField(null=True)),
            ],
        ),
    ]
