# Generated by Django 4.1 on 2022-12-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_employeeasset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset',
            new_name='name',
        ),
    ]
